### ISSUE TITLE
pxe with uefi

### ISSUE THREAD

**Issue by pippozq** [geneC/syslinux#3]
when using bios mode,everything is fine, but when using uefi mode, a problem comes.
i downloaded the version 6.03,  then copy  efi64/com32/elflink/ldlinux/ldlinux.e64  and efi64/efi/syslinux.efi to /var/lib/tftpboot/ 
when booting
Loading /images/centos7.0-x86_64/vmlinuz...ok
Loading /images/centos7.0-x86_64/initrd.img....   this step will lasts 6 min at least  and it just lasts 5 sec at most when i using bios mode with pxelinux.0.  
i changed the version 6.0,6.01,6.02  even can't start.....

**Comment by morteryler** [comment]
version 1.5 worked

**Comment by pippozq** [comment]
pretty cool,thanks lot
